# CLAUDE_ADDED: サンプル設定ファイル
# Transformer Base End-to-End VAE実験設定

experiment:
  name: "transformer_base_e2e_vae_test"
  description: "Transformer Base End-to-End VAEの基本実験"
  priority: 1
  tags: ["baseline", "transformer", "e2e"]
  dependencies: []

# モデル設定
model:
  class_name: "EndToEndTransformerVAE"
  file_path: "PredictiveLatentSpaceNavigationModel/TransformerBaseEndToEndVAE/models/TransformerBaseEndToEndVAE.py"
  
  # モデルパラメータ
  input_dim: 6
  d_model: 256
  n_heads: 8
  n_encoder_layers: 6
  n_decoder_layers: 3
  style_latent_dim: 64
  skill_latent_dim: 64
  beta: 0.0001
  contrastive_weight: 0.1

# 学習設定
training:
  num_epochs: 500
  batch_size: 16
  learning_rate: 0.0002
  weight_decay: 0.00001
  
  optimizer: "AdamW"
  scheduler: "CosineAnnealingWarmRestarts"
  scheduler_T_0: 30
  scheduler_T_mult: 2
  scheduler_eta_min: 0.00001
  early_stopping: true
  patience: 50
  min_delta: 0.0001
  monitor: "val_total_loss"
  mode: "min"
  restore_best_weights: true
  verbose: true
  save_best_model: true
  
  # 段階的学習設定
  staged_training: true
  stage1_epochs: 50  # 基本表現学習
  stage2_epochs: 30  # スタイル分離
  stage3_epochs: 20  # 統合最適化

# データ設定
data:
  type: "generalized_coordinate"
  data_path: "PredictiveLatentSpaceNavigationModel/DataPreprocess/ForGeneralizedCoordinate"
  test_size: 0.2
  val_size: 0.1
  random_seed: 42
  
  # データ前処理
  normalize: true
  augmentation: false
  
  # DataLoader設定
  num_workers: 4
  pin_memory: true
  shuffle: true

# 評価設定
evaluation:
  # 基本評価
  reconstruction_quality: true
  latent_space_analysis: false
  comprehensive_latent_analysis: true
  
  # 高度な評価
  skill_axis_analysis: false
  style_separation_analysis: true
  
  # 可視化設定
  create_plots: true
  save_trajectories: true
  generate_examples: true
  
  # カスタム評価器
  custom_evaluators: []

# 出力設定
output:
  base_dir: "PredictiveLatentSpaceNavigationModel/TransformerBaseEndToEndVAE/outputs"
  save_model: true
  save_checkpoints: true
  checkpoint_interval: 10
  
  # ログ設定
  log_level: "INFO"
  tensorboard: false
  wandb: false
  
  # 結果保存
  save_predictions: true
  save_embeddings: true
  create_report: true

# システム設定
system:
  device: "auto"  # "cuda", "cpu", "auto"
  mixed_precision: false
  deterministic: true
  benchmark: false
  
  # 並列処理
  dataloader_workers: 2
  pin_memory: true