# CLAUDE_ADDED: ベストモデル保存機能テスト用設定ファイル
experiment:
  name: "best_model_save_test"
  description: "ベストモデル.pthファイル保存機能のテスト"
  priority: 1
  tags: ["test", "best_model", "early_stopping"]
  dependencies: []

# モデル設定
model:
  class_name: "MotionTransformerVAE"
  file_path: "PredictiveLatentSpaceNavigationModel/TransformerBaseEndToEndVAE/models/signature_transformer_vae.py"
  
  input_dim: 6
  seq_len: 100
  hidden_dim: 128
  style_latent_dim: 16
  skill_latent_dim: 4
  beta: 0.00001
  n_layers: 4
  n_heads: 8
  max_len: 100
  contrastive_weight: 0.1
  signature_weight: 0.8
  use_triplet: false

# 学習設定（ベストモデル保存テスト用）
training:
  num_epochs: 20
  batch_size: 16
  learning_rate: 0.001
  weight_decay: 0.00001
  
  optimizer: "AdamW"
  scheduler: "CosineAnnealingWarmRestarts"
  scheduler_T_0: 5
  scheduler_T_mult: 2
  scheduler_eta_min: 0.0001
  
  # CLAUDE_ADDED: ベストモデル保存機能のテスト設定
  early_stopping: true
  patience: 5
  min_delta: 0.001
  monitor: "val_total_loss"
  mode: "min"
  restore_best_weights: true
  verbose: true
  save_best_model: true  # ベストモデル保存を有効化
  
  staged_training: false

# データ設定
data:
  type: "generalized_coordinate"
  data_path: "PredictiveLatentSpaceNavigationModel/DataPreprocess/ForGeneralizedCoordinate"
  test_size: 0.2
  val_size: 0.1
  random_seed: 42
  
  normalize: true
  augmentation: false
  
  num_workers: 2
  pin_memory: true
  shuffle: true

# 評価設定（最小限）
evaluation:
  reconstruction_quality: false
  latent_space_analysis: false
  comprehensive_latent_analysis: false
  
  skill_axis_analysis: false
  style_separation_analysis: false
  
  create_plots: false
  save_trajectories: false
  generate_examples: false
  
  custom_evaluators: []

# 出力設定
output:
  base_dir: "PredictiveLatentSpaceNavigationModel/TransformerBaseEndToEndVAE/outputs"
  save_model: false
  save_checkpoints: false
  checkpoint_interval: 10
  
  log_level: "INFO"
  tensorboard: false
  wandb: false
  
  save_predictions: false
  save_embeddings: false
  create_report: false

# システム設定
system:
  device: "auto"
  mixed_precision: false
  deterministic: true
  benchmark: false
  
  dataloader_workers: 2
  pin_memory: true