# CLAUDE_ADDED
# Hydra configuration for DiffWave trajectory generation model

defaults:
  - _self_

# Model configuration
model:
  input_dim: 2
  condition_dim: 5  # Will be auto-detected from data
  residual_channels: 64
  skip_channels: 64
  condition_channels: 128
  num_layers: 20
  cycles: 6
  time_embed_dim: 128

# Training configuration
training:
  batch_size: 32
  epochs: 300
  learning_rate: 1e-4
  gradient_clip: 1.0
  save_interval: 50
  use_dummy: false
  # Early stopping configuration
  early_stopping:
    enabled: true
    patience: 30  # DiffWaveは収束が遅い場合があるので少し長めに
    min_delta: 1e-6
    restore_best_weights: true

# Data configuration  
data:
  train_data: "/data/Datasets/overfitting_dataset.npz"
  val_data: null  # If null, will split from train_data
  val_split_ratio: 0.2

# Diffusion scheduler configuration
scheduler:
  num_timesteps: 1000
  beta_start: 0.0001
  beta_end: 0.02

# Generation configuration
generation:
  method: "ddpm"  # ddpm or ddim
  num_inference_steps: null  # null means use all timesteps
  seq_len: 101
  num_samples: 8

# Device configuration
device: "cuda"

# Output directories
output:
  checkpoint_dir: "outputs/checkpoints"
  generation_dir: "outputs/generated_trajectories"
  overfit_dir: "outputs/overfit_results"
  mlflow_tracking_uri: "outputs/mlflow"
  experiment_name: "diffwave_trajectory"

# MLFlow configuration
mlflow:
  tracking_uri: "outputs/mlflow"
  experiment_name: "diffwave_trajectory_experiments"
  run_name: null  # If null, will be auto-generated
  log_model: true
  log_artifacts: true

# Evaluation configuration
evaluation:
  metrics:
    - "trajectory_diversity"
    - "condition_consistency" 
    - "trajectory_smoothness"
    - "endpoint_accuracy"
  visualization:
    save_plots: true
    plot_samples: 16