# Transformer Base Signature VAE 実験設定
experiment:
  description: "Transformer Base Signature VAE テスト実験"
  tags: ["test", "transformer", "signature_vae"]

data:
  data_path: PredictiveLatentSpaceNavigationModel/DataPreprocess/ForGeneralizedCoordinate

model:
  input_dim: 6
  seq_len: 100
  hidden_dim: 128
  style_latent_dim: 32
  skill_latent_dim: 64
  beta: 0.001
  n_layers: 6
  contrastive_weight: 1.0
  use_triplet: false

training:
  batch_size: 32
  num_epochs: 200
  lr: 0.0001
  weight_decay: 0.0001
  clip_grad_norm: 1.0
  warmup_epochs: 500
  scheduler_T_0: 10
  scheduler_T_mult: 2
  scheduler_eta_min: 0.00001
  patience: 50

logging:
  output_dir: "PredictiveLatentSpaceNavigationModel/TransformerBaseSignatureVAE/outputs"
  save_every: 10
  log_every: 5