config_path: PredictiveLatentSpaceNavigationModel/hierarchical_vae_generalized_coordinate/configs
data:
  data_path: PredictiveLatentSpaceNavigationModel/DataPreprocess/ForGeneralizedCoordinate
model:
  input_dim: 6
  seq_len: 100
  hidden_dim: 256
  primitive_latent_dim: 64
  skill_latent_dim: 32
  style_latent_dim: 32
  beta_primitive: 1.0
  beta_skill: 0.1
  beta_style: 0.005
  precision_lr: 0.1
training:
  batch_size: 8
  num_epochs: 200
  lr: 0.001
  weight_decay: 1.0e-05
  clip_grad_norm: 1.0
  warmup_epochs: 10
  scheduler_T_0: 25
  scheduler_T_mult: 2
  scheduler_eta_min: 5.0e-07
  patience: 50
logging:
  output_dir: PredictiveLatentSpaceNavigationModel/hierarchical_vae_generalized_coordinate/outputs
hierarchical_settings:
  primitive_learning_start: 0.0
  skill_learning_start: 0.15
  style_learning_start: 0.4
  prediction_error_weights:
    level1: 10.0
    level2: 1.0
    level3: 0.1
  exemplar_generation:
    skill_enhancement_factor: 0.1
    style_preservation_weight: 1.0
    max_enhancement_steps: 5
evaluation:
  disentanglement_metrics:
  - style_subject_separation
  - skill_performance_correlation
  - primitive_reconstruction_quality
  visualization:
    pca_components: 2
    save_individual_trajectories: true
    save_exemplar_comparisons: true
experiment:
  description: 'Ablation: No hierarchy (standard VAE)'
  tags:
  - hierarchical_vae
  - validation
  - hyperparameter_search
  - ablation_no_hierarchy
