# CLAUDE_ADDED
# Hydra configuration for Transformer trajectory generation model

defaults:
  - _self_

# Model configuration
model:
  input_dim: 2
  condition_dim: 5  # Will be auto-detected from data
  d_model: 256
  nhead: 8
  num_encoder_layers: 6
  num_decoder_layers: 6
  dim_feedforward: 1024
  max_seq_len: 101
  dropout: 0.1

# Training configuration
training:
  batch_size: 32
  epochs: 200
  learning_rate: 1e-4
  weight_decay: 1e-4
  gradient_clip: 1.0
  save_interval: 20
  use_dummy: true
  # Early stopping configuration
  early_stopping:
    enabled: true
    patience: 25  # Transformerは収束が遅い場合があるので長めに
    min_delta: 1e-6
    restore_best_weights: true

# Data configuration  
data:
  train_data: "/data/Datasets/overfitting_dataset.npz"
  val_data: null  # If null, will split from train_data
  val_split_ratio: 0.2

# Generation configuration
generation:
  max_length: 101
  num_samples: 8
  use_start_points: true  # 開始点を使用するか
  num_start_points: 3    # 開始点の数

# Device configuration
device: "cuda"

# Output directories
output:
  checkpoint_dir: "checkpoints"
  mlflow_tracking_uri: "mlruns"
  experiment_name: "transformer_trajectory"

# MLFlow configuration
mlflow:
  tracking_uri: "mlruns"
  experiment_name: "transformer_trajectory_experiments"
  run_name: null  # If null, will be auto-generated
  log_model: true
  log_artifacts: true

# Evaluation configuration
evaluation:
  metrics:
    - "trajectory_diversity"
    - "condition_consistency" 
    - "trajectory_smoothness"
    - "endpoint_accuracy"
  visualization:
    save_plots: true
    plot_samples: 16