# Transformer Base Signature VAE 実験設定
experiment:
  description: "Transformer Base Signature VAE テスト実験"
  tags: ["test", "transformer", "signature_vae"]

data:
  data_path: "PredictiveLatentSpaceNavigationModel/DataPreprocess/ForSignatureVAE/processed_trajectory_data_with_signature.parquet"

model:
  input_dim: 4
  seq_len: 200
  hidden_dim: 128
  style_latent_dim: 32
  skill_latent_dim: 64
  beta: 1.0
  n_layers: 4
  contrastive_weight: 1.0
  use_triplet: true

training:
  batch_size: 32
  num_epochs: 50
  lr: 0.001
  weight_decay: 0.0001
  clip_grad_norm: 1.0
  warmup_epochs: 5
  scheduler_T_0: 10
  scheduler_T_mult: 2
  scheduler_eta_min: 0.00001
  patience: 10

logging:
  output_dir: "PredictiveLatentSpaceNavigationModel/TransformerBaseSignatureVAE/outputs"
  save_every: 10
  log_every: 5