information:
  name: "Calculate Skill Score promax Win 5"
  description: "安定したスキルスコアの算出"

pre_process:
  target_seq_len: 100
  interpolate_method: linear # linear, spline

analysis:
  anova_skill_metrics: true
  factorize_skill_metrics: true
  standardize_metrics: true

data:
  raw_data_dir: "../../data/RawDatas"
  output_dir: "PredictiveLatentSpaceNavigationModel/DataPreprocess/AnalysisResults"
  make_dataset: false
