information:
  name: "Dataset Generation Test"
  description: "データセット作成のテスト"

pre_process:
  target_seq_len: 100
  interpolate_method: linear # linear, spline

analysis:
  anova_skill_metrics: true
  factorize_skill_metrics: true
  standardize_metrics: true

data:
  raw_data_dir: "../../data/RawDatas"
  output_dir: "PredictiveLatentSpaceNavigationModel/DataPreprocess/AnalysisResults"
  make_dataset: true
