data:
  data_path: ../../data/Datasets/overfitting_dataset.npz
logging:
  log_interval: 10
  output_dir: HybridModelExperiment/outputs
  save_interval: 20

# モデルの定義セクション
model:
  # 1.アーキテクチャの名前を指定
  architecture:
    low_freq_model: 'CurveLowFreqTransformer'
    high_freq_model: 'UNet1DForTrajectory'
    decomposer_model: 'ImprovedDataDecomposer'

  # 2. 各サブモデルに渡すパラメータ
  decomposer_params:
    window_size: 10
    learnable: true
    decomposition_method: 'adaptive'

  low_freq_params:
    dim_head: 32
    heads: 8
    num_layers: 4

  high_freq_params:
    base_channels: 32
    num_resolutions: 3

  # 3. モデル全体で共通のパラメータ
  input_dim: 2
  condition_dim: 5
  time_embed_dim: 128

training:
  augment_after_epoch: 20
  batch_size: 32
  clip_grad_norm: 1.0
  lr_decomposer: 0.0001
  lr_high_freq: 0.0005
  lr_low_freq: 0.001
  num_epochs: 20
  scheduler_T_0: 20
  scheduler_T_mult: 2
  scheduler_eta_min: 1.0e-06
  warmup_epochs: 10
  weight_decay: 0.0001
