# CLAUDE_ADDED
# Hydra configuration for UNet diffusion model training and evaluation

defaults:
  - _self_

# Model configuration
model:
  input_dim: 2
  condition_dim: 5  # Will be auto-detected from data
  time_embed_dim: 128
  base_channels: 64

# Training configuration
training:
  batch_size: 32
  epochs: 100
  learning_rate: 1e-4
  save_interval: 10
  use_dummy: false

# Data configuration  
data:
  train_data: "data/Datasets/overfitting_dataset_cond_3.npz"
  val_data: null  # If null, will split from train_data
  val_split_ratio: 0.2

# Diffusion scheduler configuration
scheduler:
  num_timesteps: 1000
  beta_start: 0.0001
  beta_end: 0.02

# Generation configuration
generation:
  method: "ddpm"  # ddpm or ddim
  num_inference_steps: null  # null means use all timesteps
  seq_len: 101
  num_samples: 8

# Device configuration
device: "cuda"

# Output directories
output:
  checkpoint_dir: "checkpoints"
  mlflow_tracking_uri: "mlruns"
  experiment_name: "unet_diffusion"

# MLFlow configuration
mlflow:
  tracking_uri: "mlruns"
  experiment_name: "unet_diffusion_experiments"
  run_name: null  # If null, will be auto-generated
  log_model: true
  log_artifacts: true

# Evaluation configuration
evaluation:
  metrics:
    - "trajectory_diversity"
    - "condition_consistency" 
    - "trajectory_smoothness"
    - "endpoint_accuracy"
  visualization:
    save_plots: true
    plot_samples: 16