# CLAUDE_ADDED
# Hydra configuration for UNet diffusion model training and evaluation

defaults:
  - _self_

# Model configuration
model:
  input_dim: 2
  condition_dim: 5  # Will be auto-detected from data
  time_embed_dim: 128
  base_channels: 128

# Training configuration
training:
  batch_size: 32
  epochs: 300
  learning_rate: 2e-5
  fourier_loss_weight: 10.0
  save_interval: 10
  use_dummy: false
  # Early stopping configuration
  early_stopping:
    enabled: true
    patience: 20  # エポック数
    min_delta: 1e-6  # 最小改善量
    restore_best_weights: true  # 最良の重みを復元

# Data configuration  
data:
  train_data: "/data/Datasets/overfitting_dataset.npz"  # 絶対パス使用
  val_data: null  # If null, will split from train_data
  val_split_ratio: 0.2

# Diffusion scheduler configuration
scheduler:
  num_timesteps: 1000
  beta_start: 0.0001
  beta_end: 0.02

# Generation configuration
generation:
  method: "ddpm"  # ddpm or ddim
  num_inference_steps: null  # null means use all timesteps
  seq_len: 101
  num_samples: 8

# Device configuration
device: "cuda"

# Output directories
output:
  checkpoint_dir: "outputs/checkpoints"
  generated_dir: "outputs/generated_trajectories" 
  overfit_dir: "outputs/overfit_results"
  mlflow_tracking_uri: "outputs/mlflow"
  experiment_name: "unet_diffusion"

# MLFlow configuration
mlflow:
  tracking_uri: "outputs/mlflow"
  experiment_name: "unet_diffusion_experiments"
  run_name: null  # If null, will be auto-generated
  log_model: true
  log_artifacts: true

# Evaluation configuration
evaluation:
  metrics:
    - "trajectory_diversity"
    - "condition_consistency" 
    - "trajectory_smoothness"
    - "endpoint_accuracy"
  visualization:
    save_plots: true
    plot_samples: 16