config_path: PredictiveLatentSpaceNavigationModel/beta_vae_generalized_coordinate/configs
data:
  data_path: PredictiveLatentSpaceNavigationModel/DataPreprocess/ForGeneralizedCoordinate
model:
  input_dim: 6
  seq_len: 100
  hidden_dim: 256
  style_latent_dim: 32
  skill_latent_dim: 16
  beta: 0.1
  n_layers: 2
  contrastive_weight: 5.0
  use_triplet: false
training:
  batch_size: 32
  num_epochs: 200
  lr: 2.0e-04
  weight_decay: 1.0e-05
  clip_grad_norm: 1.0
  warmup_epochs: 10
  scheduler_T_0: 25
  scheduler_T_mult: 2
  scheduler_eta_min: 5.0e-07
  patience: 30
logging:
  output_dir: PredictiveLatentSpaceNavigationModel/beta_vae_generalized_coordinate/outputs
evaluation:
  disentanglement_metrics:
  - style_subject_separation
  - skill_performance_correlation
  visualization:
    pca_components: 2
    save_individual_trajectories: true
    save_exemplar_comparisons: true
experiment:
  description: 'Ablation: No hierarchy (standard VAE)'
  tags:
  - beta_vae_generalized_coordinate
  - validation
  - hyperparameter_search
  - ablation_no_hierarchy
